sonar.projectKey=chak-tasklist-backend
sonar.projectName=chak-tasklist-backend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.junit.reportPaths=reports/junit.xml

sonar.coverage.exclusions=src/__tests__/**,src/__tests__/e2e/setup.ts
